In [2]:
import pandas as pd
import numpy as np

In [3]:
titanic = pd.read_csv('./dataset/titanic.csv')
titanic

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [4]:
# info
titanic.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB

In [5]:
# titanic.head() # starting 5 rows by default
titanic.head(10)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
5,6,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,Q
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S
7,8,0,3,"Palsson, Master. Gosta Leonard",male,2.0,3,1,349909,21.0750,NaN,S
8,9,1,3,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,27.0,0,2,347742,11.1333,NaN,S
9,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0,1,0,237736,30.0708,NaN,C

In [6]:
titanic.tail()# last 5 rows
titanic.tail(9)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
882,883,0,3,"Dahlberg, Miss. Gerda Ulrika",female,22.0,0,0,7552,10.5167,NaN,S
883,884,0,2,"Banfield, Mr. Frederick James",male,28.0,0,0,C.A./SOTON 34068,10.5000,NaN,S
884,885,0,3,"Sutehall, Mr. Henry Jr",male,25.0,0,0,SOTON/OQ 392076,7.0500,NaN,S
885,886,0,3,"Rice, Mrs. William (Margaret Norton)",female,39.0,0,5,382652,29.1250,NaN,Q
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [7]:
titanic.describe()

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
count,891.000000,891.000000,891.000000,714.000000,891.000000,891.000000,891.000000
mean,446.000000,0.383838,2.308642,29.699118,0.523008,0.381594,32.204208
std,257.353842,0.486592,0.836071,14.526497,1.102743,0.806057,49.693429
min,1.000000,0.000000,1.000000,0.420000,0.000000,0.000000,0.000000
25%,223.500000,0.000000,2.000000,20.125000,0.000000,0.000000,7.910400
50%,446.000000,0.000000,3.000000,28.000000,0.000000,0.000000,14.454200
75%,668.500000,1.000000,3.000000,38.000000,1.000000,0.000000,31.000000
max,891.000000,1.000000,3.000000,80.000000,8.000000,6.000000,512.329200

In [8]:
titanic.shape

(891, 12)

In [9]:
titanic.values

array([[1, 0, 3, ..., 7.25, nan, 'S'],
       [2, 1, 1, ..., 71.2833, 'C85', 'C'],
       [3, 1, 3, ..., 7.925, nan, 'S'],
       ...,
       [889, 0, 3, ..., 23.45, nan, 'S'],
       [890, 1, 1, ..., 30.0, 'C148', 'C'],
       [891, 0, 3, ..., 7.75, nan, 'Q']], shape=(891, 12), dtype=object)

In [10]:
titanic.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')

In [11]:
titanic.index

RangeIndex(start=0, stop=891, step=1)

In [12]:
titanic.sort_values(by='Age') # default ascending

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
803,804,1,3,"Thomas, Master. Assad Alexander",male,0.42,0,1,2625,8.5167,NaN,C
755,756,1,2,"Hamalainen, Master. Viljo",male,0.67,1,1,250649,14.5000,NaN,S
644,645,1,3,"Baclini, Miss. Eugenie",female,0.75,2,1,2666,19.2583,NaN,C
469,470,1,3,"Baclini, Miss. Helene Barbara",female,0.75,2,1,2666,19.2583,NaN,C
78,79,1,2,"Caldwell, Master. Alden Gates",male,0.83,0,2,248738,29.0000,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
859,860,0,3,"Razi, Mr. Raihed",male,NaN,0,0,2629,7.2292,NaN,C
863,864,0,3,"Sage, Miss. Dorothy Edith ""Dolly""",female,NaN,8,2,CA. 2343,69.5500,NaN,S
868,869,0,3,"van Melkebeke, Mr. Philemon",male,NaN,0,0,345777,9.5000,NaN,S
878,879,0,3,"Laleff, Mr. Kristo",male,NaN,0,0,349217,7.8958,NaN,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S

In [13]:
titanic.sort_values(by='Age',ascending=False)  # descending

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
630,631,1,1,"Barkworth, Mr. Algernon Henry Wilson",male,80.0,0,0,27042,30.0000,A23,S
851,852,0,3,"Svensson, Mr. Johan",male,74.0,0,0,347060,7.7750,NaN,S
493,494,0,1,"Artagaveytia, Mr. Ramon",male,71.0,0,0,PC 17609,49.5042,NaN,C
96,97,0,1,"Goldschmidt, Mr. George B",male,71.0,0,0,PC 17754,34.6542,A5,C
116,117,0,3,"Connors, Mr. Patrick",male,70.5,0,0,370369,7.7500,NaN,Q
...,...,...,...,...,...,...,...,...,...,...,...,...
859,860,0,3,"Razi, Mr. Raihed",male,NaN,0,0,2629,7.2292,NaN,C
863,864,0,3,"Sage, Miss. Dorothy Edith ""Dolly""",female,NaN,8,2,CA. 2343,69.5500,NaN,S
868,869,0,3,"van Melkebeke, Mr. Philemon",male,NaN,0,0,345777,9.5000,NaN,S
878,879,0,3,"Laleff, Mr. Kristo",male,NaN,0,0,349217,7.8958,NaN,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S

In [14]:
titanic.sort_values(['Age','Fare'],ascending=False)  # descending

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
630,631,1,1,"Barkworth, Mr. Algernon Henry Wilson",male,80.0,0,0,27042,30.0000,A23,S
851,852,0,3,"Svensson, Mr. Johan",male,74.0,0,0,347060,7.7750,NaN,S
493,494,0,1,"Artagaveytia, Mr. Ramon",male,71.0,0,0,PC 17609,49.5042,NaN,C
96,97,0,1,"Goldschmidt, Mr. George B",male,71.0,0,0,PC 17754,34.6542,A5,C
116,117,0,3,"Connors, Mr. Patrick",male,70.5,0,0,370369,7.7500,NaN,Q
...,...,...,...,...,...,...,...,...,...,...,...,...
481,482,0,2,"Frost, Mr. Anthony Wood ""Archie""",male,NaN,0,0,239854,0.0000,NaN,S
633,634,0,1,"Parr, Mr. William Henry Marsh",male,NaN,0,0,112052,0.0000,NaN,S
674,675,0,2,"Watson, Mr. Ennis Hastings",male,NaN,0,0,239856,0.0000,NaN,S
732,733,0,2,"Knight, Mr. Robert J",male,NaN,0,0,239855,0.0000,NaN,S
815,816,0,1,"Fry, Mr. Richard",male,NaN,0,0,112058,0.0000,B102,S

In [15]:
titanic.sort_values(['Age','Fare'],ascending=False,na_position='first')  # descending

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
557,558,0,1,"Robbins, Mr. Victor",male,NaN,0,0,PC 17757,227.5250,NaN,C
527,528,0,1,"Farthing, Mr. John",male,NaN,0,0,PC 17483,221.7792,C95,S
31,32,1,1,"Spencer, Mrs. William Augustus (Marie Eugenie)",female,NaN,1,0,PC 17569,146.5208,B78,C
334,335,1,1,"Frauenthal, Mrs. Henry William (Clara Heinshei...",female,NaN,1,0,PC 17611,133.6500,NaN,S
306,307,1,1,"Fleming, Miss. Margaret",female,NaN,0,0,17421,110.8833,NaN,C
...,...,...,...,...,...,...,...,...,...,...,...,...
831,832,1,2,"Richards, Master. George Sibley",male,0.83,1,1,29106,18.7500,NaN,S
469,470,1,3,"Baclini, Miss. Helene Barbara",female,0.75,2,1,2666,19.2583,NaN,C
644,645,1,3,"Baclini, Miss. Eugenie",female,0.75,2,1,2666,19.2583,NaN,C
755,756,1,2,"Hamalainen, Master. Viljo",male,0.67,1,1,250649,14.5000,NaN,S
803,804,1,3,"Thomas, Master. Assad Alexander",male,0.42,0,1,2625,8.5167,NaN,C

In [16]:
titanic.sort_values(['Age','Fare'],ascending=[False,True])  # descending

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
630,631,1,1,"Barkworth, Mr. Algernon Henry Wilson",male,80.0,0,0,27042,30.0000,A23,S
851,852,0,3,"Svensson, Mr. Johan",male,74.0,0,0,347060,7.7750,NaN,S
96,97,0,1,"Goldschmidt, Mr. George B",male,71.0,0,0,PC 17754,34.6542,A5,C
493,494,0,1,"Artagaveytia, Mr. Ramon",male,71.0,0,0,PC 17609,49.5042,NaN,C
116,117,0,3,"Connors, Mr. Patrick",male,70.5,0,0,370369,7.7500,NaN,Q
...,...,...,...,...,...,...,...,...,...,...,...,...
306,307,1,1,"Fleming, Miss. Margaret",female,NaN,0,0,17421,110.8833,NaN,C
334,335,1,1,"Frauenthal, Mrs. Henry William (Clara Heinshei...",female,NaN,1,0,PC 17611,133.6500,NaN,S
31,32,1,1,"Spencer, Mrs. William Augustus (Marie Eugenie)",female,NaN,1,0,PC 17569,146.5208,B78,C
527,528,0,1,"Farthing, Mr. John",male,NaN,0,0,PC 17483,221.7792,C95,S
557,558,0,1,"Robbins, Mr. Victor",male,NaN,0,0,PC 17757,227.5250,NaN,C

In [17]:
titanic['Age']

0      22.0
1      38.0
2      26.0
3      35.0
4      35.0
       ...
886    27.0
887    19.0
888     NaN
889    26.0
890    32.0
Name: Age, Length: 891, dtype: float64

In [18]:
titanic[['Age','Name']]

      Age                                               Name
0    22.0                            Braund, Mr. Owen Harris
1    38.0  Cumings, Mrs. John Bradley (Florence Briggs Th...
2    26.0                             Heikkinen, Miss. Laina
3    35.0       Futrelle, Mrs. Jacques Heath (Lily May Peel)
4    35.0                           Allen, Mr. William Henry
..    ...                                                ...
886  27.0                              Montvila, Rev. Juozas
887  19.0                       Graham, Miss. Margaret Edith
888   NaN           Johnston, Miss. Catherine Helen "Carrie"
889  26.0                              Behr, Mr. Karl Howell
890  32.0                                Dooley, Mr. Patrick

[891 rows x 2 columns]

In [19]:
wanted_columns = ['Name','Survived','Sex','Age']
titanic[wanted_columns]

                                                  Name  Survived     Sex   Age
0                              Braund, Mr. Owen Harris         0    male  22.0
1    Cumings, Mrs. John Bradley (Florence Briggs Th...         1  female  38.0
2                               Heikkinen, Miss. Laina         1  female  26.0
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)         1  female  35.0
4                             Allen, Mr. William Henry         0    male  35.0
..                                                 ...       ...     ...   ...
886                              Montvila, Rev. Juozas         0    male  27.0
887                       Graham, Miss. Margaret Edith         1  female  19.0
888           Johnston, Miss. Catherine Helen "Carrie"         0  female   NaN
889                              Behr, Mr. Karl Howell         1    male  26.0
890                                Dooley, Mr. Patrick         0    male  32.0

[891 rows x 4 columns]

In [20]:
titanic['Age'] <25

0       True
1      False
2      False
3      False
4      False
       ...
886    False
887     True
888    False
889    False
890    False
Name: Age, Length: 891, dtype: bool

In [21]:
titanic[titanic['Age'] <25]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
7,8,0,3,"Palsson, Master. Gosta Leonard",male,2.0,3,1,349909,21.0750,NaN,S
9,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0,1,0,237736,30.0708,NaN,C
10,11,1,3,"Sandstrom, Miss. Marguerite Rut",female,4.0,1,1,PP 9549,16.7000,G6,S
12,13,0,3,"Saundercock, Mr. William Henry",male,20.0,0,0,A/5. 2151,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
875,876,1,3,"Najib, Miss. Adele Kiamie ""Jane""",female,15.0,0,0,2667,7.2250,NaN,C
876,877,0,3,"Gustafsson, Mr. Alfred Ossian",male,20.0,0,0,7534,9.8458,NaN,S
877,878,0,3,"Petroff, Mr. Nedelio",male,19.0,0,0,349212,7.8958,NaN,S
882,883,0,3,"Dahlberg, Miss. Gerda Ulrika",female,22.0,0,0,7552,10.5167,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S

In [22]:
youngers = titanic['Age'] <25
survived= titanic['Survived'] ==1
titanic[youngers & survived]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
9,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0,1,0,237736,30.0708,NaN,C
10,11,1,3,"Sandstrom, Miss. Marguerite Rut",female,4.0,1,1,PP 9549,16.7000,G6,S
22,23,1,3,"McGowan, Miss. Anna ""Annie""",female,15.0,0,0,330923,8.0292,NaN,Q
39,40,1,3,"Nicola-Yarred, Miss. Jamila",female,14.0,1,0,2651,11.2417,NaN,C
43,44,1,2,"Laroche, Miss. Simonne Marie Anne Andree",female,3.0,1,2,SC/Paris 2123,41.5792,NaN,C
...,...,...,...,...,...,...,...,...,...,...,...,...
855,856,1,3,"Aks, Mrs. Sam (Leah Rosen)",female,18.0,0,1,392091,9.3500,NaN,S
858,859,1,3,"Baclini, Mrs. Solomon (Latifa Qurban)",female,24.0,0,3,2666,19.2583,NaN,C
869,870,1,3,"Johnson, Master. Harold Theodor",male,4.0,1,1,347742,11.1333,NaN,S
875,876,1,3,"Najib, Miss. Adele Kiamie ""Jane""",female,15.0,0,0,2667,7.2250,NaN,C
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S

In [23]:
titanic[titanic['Pclass'].isin([2,3])]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
5,6,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,Q
7,8,0,3,"Palsson, Master. Gosta Leonard",male,2.0,3,1,349909,21.0750,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
884,885,0,3,"Sutehall, Mr. Henry Jr",male,25.0,0,0,SOTON/OQ 392076,7.0500,NaN,S
885,886,0,3,"Rice, Mrs. William (Margaret Norton)",female,39.0,0,5,382652,29.1250,NaN,Q
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [24]:
titanic['Discount Fare'] = titanic['Fare'] / 10

In [25]:
titanic

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Discount Fare
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,0.72500
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,7.12833
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,0.79250
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,5.31000
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S,0.80500
...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S,1.30000
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S,3.00000
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S,2.34500
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C,3.00000
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q,0.77500

In [26]:
# if age < 10 then 25%
# if age 20 & 50 then 10 % 
# if age > 50 then 50%

In [27]:
def apply_discount(age):
    if age < 10 :
        return 0.25
    elif 20 <= age <= 50:
        return 0.1
    elif age > 50:
        return 0.5
            
titanic['Discount'] = titanic['Age'].apply(apply_discount)
titanic['Discount Fare'] = titanic['Fare'] * (1-titanic['Discount']) # 1 - 0.1 == 0.9
titanic[['Name','Fare','Age','Discount','Discount Fare']]

,Name,Fare,Age,Discount,Discount Fare
0,"Braund, Mr. Owen Harris",7.2500,22.0,0.1,6.52500
1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",71.2833,38.0,0.1,64.15497
2,"Heikkinen, Miss. Laina",7.9250,26.0,0.1,7.13250
3,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",53.1000,35.0,0.1,47.79000
4,"Allen, Mr. William Henry",8.0500,35.0,0.1,7.24500
...,...,...,...,...,...
886,"Montvila, Rev. Juozas",13.0000,27.0,0.1,11.70000
887,"Graham, Miss. Margaret Edith",30.0000,19.0,NaN,NaN
888,"Johnston, Miss. Catherine Helen ""Carrie""",23.4500,NaN,NaN,NaN
889,"Behr, Mr. Karl Howell",30.0000,26.0,0.1,27.00000
890,"Dooley, Mr. Patrick",7.7500,32.0,0.1,6.97500

In [28]:
titanic[titanic.Age < 20].sort_values('Age', ascending=False) # Descending

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Discount Fare,Discount
136,137,1,1,"Newsom, Miss. Helen Monypeny",female,19.00,0,2,11752,26.2833,D47,S,NaN,NaN
67,68,0,3,"Crease, Mr. Ernest James",male,19.00,0,0,S.P. 3464,8.1583,NaN,S,NaN,NaN
44,45,1,3,"Devaney, Miss. Margaret Delia",female,19.00,0,0,330958,7.8792,NaN,Q,NaN,NaN
27,28,0,1,"Fortune, Mr. Charles Alexander",male,19.00,3,2,19950,263.0000,C23 C25 C27,S,NaN,NaN
143,144,0,3,"Burke, Mr. Jeremiah",male,19.00,0,0,365222,6.7500,NaN,Q,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
831,832,1,2,"Richards, Master. George Sibley",male,0.83,1,1,29106,18.7500,NaN,S,14.062500,0.25
469,470,1,3,"Baclini, Miss. Helene Barbara",female,0.75,2,1,2666,19.2583,NaN,C,14.443725,0.25
644,645,1,3,"Baclini, Miss. Eugenie",female,0.75,2,1,2666,19.2583,NaN,C,14.443725,0.25
755,756,1,2,"Hamalainen, Master. Viljo",male,0.67,1,1,250649,14.5000,NaN,S,10.875000,0.25
803,804,1,3,"Thomas, Master. Assad Alexander",male,0.42,0,1,2625,8.5167,NaN,C,6.387525,0.25

Aggregating Data

In [29]:
titanic['Age'].mean()

np.float64(29.69911764705882)

In [30]:
# .mean()
# .median()
# .min()
# .maxx()
# .var()
# .std()
# .sum()
# .quantile()

In [31]:
# median

# [10,20,30,40,50]
# Median value  = 30

#[10,20,30,40,50,60]
# median = 30 + 40 / 2 = 35

In [32]:
titanic['Age'].mode()

0    24.0
Name: Age, dtype: float64

In [33]:
titanic.Age.min()

np.float64(0.42)

In [34]:
titanic.Age.max()

np.float64(80.0)

In [35]:
titanic['Age'].var()

np.float64(211.01912474630802)

In [36]:
titanic['Age'].quantile(0.25) #<--Return values at the given quantile over requested axis.
# By default 0.5

np.float64(20.125)

In [38]:
titanic['Age'].quantile(0.3) #<--Return values at the given quantile over requested axis.

np.float64(22.0)

In [37]:
titanic['Age'].quantile(1) #<--Return values at the given quantile over requested axis.

np.float64(80.0)

In [ ]:
# 1st quartile 25% 0.25
# 2nd quartile 50% 
# 3rd quartile 75%
# 4th quartile 100%

.agg() method

In [ ]:
def pct_30(column):
    return column.quantile(0.3)

titanic['Age'].agg(pct_30)
# Single Operation

In [42]:
df = pd.DataFrame([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9],
                   [np.nan, np.nan, np.nan]],
                  columns=['A', 'B', 'C'])
df

     A    B    C
0  1.0  2.0  3.0
1  4.0  5.0  6.0
2  7.0  8.0  9.0
3  NaN  NaN  NaN

In [ ]:
df.agg(['sum', 'min','max','mean'])

         A     B     C
sum   12.0  15.0  18.0
min    1.0   2.0   3.0
max    7.0   8.0   9.0
mean   4.0   5.0   6.0

In [46]:
# Lambda Functions
def sum(a,b):
    return a + b

sum(1,5)
# lamdba argument : expression 
x = lambda a,b : a+b
print(x(1,3))

4

In [ ]:
def pct_30(column):
    return column.quantile(0.3)
def pct_40(column):
    return column.quantile(0.4)
def pct_75(column):
    return column.quantile(0.75)


def pct_value(column, value):
    return column.quantile(value)

titanic['Age'].agg(pct_value,value=0.4)
# titanic['Age'].agg([pct_30,pct_40,pct_75])
# titanic['Age'].agg(lambda x: x.quantile(0))

np.float64(25.0)

In [ ]:
titanic[['Age', 'Fare']].agg(lambda x: x.quantile(0.3))

Age     22.00
Fare     8.05
dtype: float64

In [ ]:
# [10,5,50,6,20,30,40,50]

cumulative statistics
.cumsum()

.cummax()

.cummin()

.cumprod()

In [60]:
titanic['Age'].sum()

np.float64(21205.17)

In [59]:
pd.DataFrame(titanic['Age'].cumsum())

          Age
0       22.00
1       60.00
2       86.00
3      121.00
4      156.00
..        ...
886  21128.17
887  21147.17
888       NaN
889  21173.17
890  21205.17

[891 rows x 1 columns]

In [67]:
titanic['CumSum'] =titanic['Age'].cumsum()

In [63]:
titanic[['Age','CumSum']].head()

    Age  CumSum
0  22.0    22.0
1  38.0    60.0
2  26.0    86.0
3  35.0   121.0
4  35.0   156.0

In [ ]:
# cummax
pd.DataFrame(titanic['Survived'].cummax())
# [10,5,50,6,20,30,40,50]

Dropping duplicate

In [ ]:
titanic.drop_duplicates(subset = "Pclass")

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Discount Fare,Discount,CumSum
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,6.52500,0.1,22.0
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,64.15497,0.1,60.0
9,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0,1,0,237736,30.0708,NaN,C,NaN,NaN,253.0

In [65]:
titanic.drop_duplicates(subset = ["Pclass", 'SibSp'])

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Discount Fare,Discount,CumSum
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,6.52500,0.10,22.00
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,64.15497,0.10,60.00
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,7.13250,0.10,86.00
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S,25.93125,0.50,210.00
7,8,0,3,"Palsson, Master. Gosta Leonard",male,2.0,3,1,349909,21.0750,NaN,S,15.80625,0.25,212.00
9,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0,1,0,237736,30.0708,NaN,C,NaN,NaN,253.00
15,16,1,2,"Hewlett, Mrs. (Mary D Kingcome)",female,55.0,0,0,248706,16.0000,NaN,S,8.00000,0.50,443.00
16,17,0,3,"Rice, Master. Eugene",male,2.0,4,1,382652,29.1250,NaN,Q,21.84375,0.25,445.00
27,28,0,1,"Fortune, Mr. Charles Alexander",male,19.0,3,2,19950,263.0000,C23 C25 C27,S,NaN,NaN,653.00
38,39,0,3,"Vander Planke, Miss. Augusta Maria",female,18.0,2,0,345764,18.0000,NaN,S,NaN,NaN,868.00
59,60,0,3,"Goodwin, Master. William Frederick",male,11.0,5,2,CA 2144,46.9000,NaN,S,NaN,NaN,1225.50
120,121,0,2,"Hickman, Mr. Stanley George",male,21.0,2,0,S.O.C. 14879,73.5000,NaN,S,66.15000,0.10,2636.33
159,160,0,3,"Sage, Master. Thomas Henry",male,NaN,8,2,CA. 2343,69.5500,NaN,S,NaN,NaN,NaN
245,246,0,1,"Minahan, Dr. William Edward",male,44.0,2,0,19928,90.0000,C78,Q,81.00000,0.10,5561.83
726,727,1,2,"Renouf, Mrs. Peter Henry (Lillian Jefferys)",female,30.0,3,0,31027,21.0000,NaN,S,18.90000,0.10,17397.25

In [66]:
pd.DataFrame(titanic['Survived'].value_counts(sort=False)) # Sort by Default True

          count
Survived
0           549
1           342

In [ ]:
pd.DataFrame(titanic['Age'].value_counts()) # Sort by Default True

       count
Age
24.00     30
22.00     27
18.00     26
28.00     25
30.00     25
...      ...
24.50      1
0.67       1
0.42       1
34.50      1
74.00      1

[88 rows x 1 columns]

In [69]:
pd.DataFrame(titanic['Age'].value_counts(sort=False))

       count
Age
22.00     27
38.00     11
26.00     18
35.00     18
54.00      8
...      ...
0.67       1
30.50      2
0.42       1
34.50      1
74.00      1

[88 rows x 1 columns]

In [ ]:
pd.DataFrame(titanic['Age'].value_counts(normalize=True))

Group summary satistics

In [71]:
titanic[titanic['Sex'] == 'male']['Age'].mean()

np.float64(30.72664459161148)

In [72]:
titanic[titanic['Sex'] == 'female']['Age'].mean()

np.float64(27.915708812260537)

titanic.groupby('Sex')['Age'].mean()

In [73]:
titanic.groupby(['Survived', 'Sex'])['Survived'].count() # < -- multiple group

Survived  Sex
0         female     81
          male      468
1         female    233
          male      109
Name: Survived, dtype: int64

In [74]:
titanic.groupby(['Sex','Survived'])['Survived'].count() # < -- multiple group

Sex     Survived
female  0            81
        1           233
male    0           468
        1           109
Name: Survived, dtype: int64

In [76]:
titanic.groupby(['Survived', 'Sex'])['Age'].agg(['mean', 'min', 'max'])# <-- multiple stats

                      mean   min   max
Survived Sex
0        female  25.046875  2.00  57.0
         male    31.618056  1.00  74.0
1        female  28.847716  0.75  63.0
         male    27.276022  0.42  80.0

In [78]:
titanic.groupby(['Survived', 'Sex'])[['Age', 'SibSp']].agg(['count', 'min', 'max'])

                  Age             SibSp
                count   min   max count min max
Survived Sex
0        female    64  2.00  57.0    81   0   8
         male     360  1.00  74.0   468   0   8
1        female   197  0.75  63.0   233   0   4
         male      93  0.42  80.0   109   0   4

Pivot tables

In [79]:
#pivot and implicitly define agffunc=np.mean
titanic.pivot_table(values = 'Age', index='Sex')

              Age
Sex
female  27.915709
male    30.726645

In [80]:
#explicitly define statistics i:e np.median
titanic.pivot_table(values= 'Age', index='Sex', aggfunc=np.median)

C:\Users\Teacher\AppData\Local\Temp\ipykernel_13832\4109502689.py:2: FutureWarning: The provided callable <function median at 0x000002607E48E7A0> is currently using DataFrameGroupBy.median. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "median" instead.
  titanic.pivot_table(values= 'Age', index='Sex', aggfunc=np.median)

         Age
Sex
female  27.0
male    29.0

In [86]:
#multiple statistics
titanic.pivot_table(values='Age', index='Sex', aggfunc=[np.std, np.median,np.mean])

C:\Users\Teacher\AppData\Local\Temp\ipykernel_13832\1923709098.py:2: FutureWarning: The provided callable <function std at 0x000002607E356CA0> is currently using DataFrameGroupBy.std. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "std" instead.
  titanic.pivot_table(values='Age', index='Sex', aggfunc=[np.std, np.median,np.mean])
C:\Users\Teacher\AppData\Local\Temp\ipykernel_13832\1923709098.py:2: FutureWarning: The provided callable <function median at 0x000002607E48E7A0> is currently using DataFrameGroupBy.median. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "median" instead.
  titanic.pivot_table(values='Age', index='Sex', aggfunc=[np.std, np.median,np.mean])
C:\Users\Teacher\AppData\Local\Temp\ipykernel_13832\1923709098.py:2: FutureWarning: The provided callable <function mean at 0x000002607E356B60> is currently using DataFrameGroupBy.mean. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "mean" instead.
  titanic.pivot_table(values='Age', index='Sex', aggfunc=[np.std, np.median,np.mean])

              std median       mean
              Age    Age        Age
Sex
female  14.110146   27.0  27.915709
male    14.678201   29.0  30.726645

In [82]:
#pivot on two varibales
titanic.pivot_table(values='Age', index='Sex', columns='Survived')
# aggfunc = np.mean

Survived          0          1
Sex
female    25.046875  28.847716
male      31.618056  27.276022

In [83]:
titanic.pivot_table(values='Age', index='Sex', columns='Survived', fill_value=0)

Survived          0          1
Sex
female    25.046875  28.847716
male      31.618056  27.276022

In [89]:
titanic.pivot_table(values='Age', index='Sex', columns='Survived', fill_value=10)

Survived          0          1
Sex
female    25.046875  28.847716
male      31.618056  27.276022

In [90]:
titanic.pivot_table(values='Age', 
                    index='Sex', 
                    columns='Survived',
                    fill_value=0,
                    margins=True,
                    margins_name='mean')

Survived          0          1       mean
Sex
female    25.046875  28.847716  27.915709
male      31.618056  27.276022  30.726645
mean      30.626179  28.343690  29.699118