### Recap
- countries
- populations

In [1]:
pop = [12, 45, 65, 78, 85]
country = ["pk", 'ind', 'rus', 'jpn', 'indo']

In [3]:
print(country.index('rus'))
print(pop[2])

2
65

This way of extracting values is not adaptable because:
- Not convenient
- Not intutive

Solution is **Dictionaries**

## Dictionaries
- Accept different type
- Keys have to be "immutable" objects ->> Error
- add values
- edit value
- **in** Keyword
- delete any element

## List vs Dictionaries

## Introudction to Pandas
- ##### Question: How can we store that data in python ? 
- Numpy Array (absolutely **NO** because in Numpy we save data of same type)

### Answer:  Pandas 
- high level  data manipulation
- Wes Mckinney
- built on Numpy
- Data Frame
- special concept of Series

## Case Study: population dataset of BRICS countries
- NOTE:
   - key (columns, label)
   - values(data, column by column)

### CREATING DATAFRAME

In [6]:
bricks = {"country": ['Brazil', 'Russia', 'India', 'China', 'South Africa'],
         "capital": ['Brasilia', 'Moscow', 'New Delhi', 'Beijing', 'Pretoria'],
         "area": [8.516, 17.100, 3.286, 9.597, 1.221],
         "population": [200.40, 143.50, 1252.00, 1357.00, 52.98]}

In [ ]:
import pandas as pd
df = pd.DataFrame(bricks)
# df

df.set_index("country", inplace=True) #Inplace makes a new copy of the instance and save the updated data there
df

                capital    area  population
country
Brazil         Brasilia   8.516      200.40
Russia           Moscow  17.100      143.50
India         New Delhi   3.286     1252.00
China           Beijing   9.597     1357.00
South Africa   Pretoria   1.221       52.98

In [36]:
car_df = pd.read_csv("./dataset/bricks.csv", index_col = 0)
# print(car_df["country", "area"])
car_df[["country", "area"]]

         country    area
BR        Brazil   8.516
RU        Russia  17.100
IN         India   3.286
CH         China   9.597
SA  South Africa   1.221

In [71]:
car_df.loc[["RU", "CH"][:]]

   country  capital    area  population
RU  Russia   Moscow  17.100       143.5
CH   China  Beijing   9.597      1357.0

# car_df.loc[["BR", "RU"]] #Value based function: loc
car_df.iloc[[0, 4]] #Integer based function: iloc
# car_df.iloc[0, 3]
car_df.iloc[:3, 2:4] #Fetching the first 3 rows and 2 columns

change index values `df.index = []`

#### another way to create DATAFRAME is through csv (comma seperated files)

assume we have **'bricks.csv'** file in our directory

### index and select data
- square brakets (type--> series) & double squrae brakets (type --> DataFrame)
- advance methods
    - loc
    - iloc

### Question What if we want specific columns and rows ?
###### Key points about [ ] square brakets

- square bralets have limited functionality
- ideally 
    - Remember **2D Numpy array** in numpy
    - ``my_arr[row, col]``
- pandas
    - ``loc``(label based)
    - ``iloc`` (index based)

In [4]:
# rows as pandas series `[]` & dataframe `[[]]`

In [5]:
# specific rows more than one

In [ ]:
# specific rows and columns

In [6]:
# try slicing with it

#### Quick Recap

- Square brakets

    - column access --> ``bricks.csv[['country', 'capital']]``
    - row access (only through slicing) --> ``bricks_csv[1:4]``
    
- loc(label-based) remeber ``arr[rows, columns]``

    - row access --> ``bricks_csv.loc[['BR', 'IN']]``
    - columns access --> ``bricks_csv.loc[:['country', 'capital']]``
    - both rows and columns --> <br>
    ``bricks_csv.loc[['BR', 'IN'], ['country', 'capital']]``

### Accessing values with iloc[]